apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: vijaytrainer/myapache:1.0
    name: test-container
    volumeMounts:
    - mountPath: /var/www/html
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /tmp
      # this field is optional
      type: Directory
