apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  namespace: qos-example
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "20Mi"
        cpu: "70m"
      requests:
        memory: "20Mi"
        cpu: "70m"
