apiVersion: v1
kind: Pod
metadata:
  name: redis-with-secrets
spec:
  containers:
    - name: myredis
      image: redis:latest
      env:
        - name: rdsusername
          valueFrom:
            secretKeyRef:
              name: hidesecrets
              key: username
        - name: rdspassword
          valueFrom:
            secretKeyRef:
              name: hidesecrets
              key: password