apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploysecretvol
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: Cmdeploy
    spec:
      containers:
      - name: containersec1
        image: redis:latest
        volumeMounts:
         - name: secvol
           mountPath: "/etc/vol"
           readOnly: true
      volumes:
       - name: secvol
         secret:
           secretName: hidesecrets