apiVersion: v1
kind: Pod
metadata:
  name: redispod
spec:
  containers:
    - name: myredis
      image: redis:latest
      env:
        - name: rdsusername
          valueFrom:
            secretKeyRef:
              name: secret1
              key: username
        - name: rdspassword
          valueFrom:
            secretKeyRef:
              name: secret2
              key: password
